# Generated by Django 4.2.1 on 2023-06-20 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_alter_genre_picture'),
        ('books', '0002_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(related_name='books_author', to='reference.author', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books_series', to='reference.series', verbose_name='Series'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books_genre', to='reference.genre', verbose_name='Genre'),
        ),
    ]
