# Generated by Django 4.2.1 on 2023-06-20 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_alter_series_name'),
        ('books', '0003_book_author_book_series_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.BigIntegerField(default=2000, verbose_name='Year book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books_series', to='reference.series', verbose_name='Series'),
        ),
    ]
