# Generated by Django 4.2.1 on 2023-06-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_year_alter_book_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dateadd',
            field=models.DateTimeField(default='2023-06-20', verbose_name='Date add'),
            preserve_default=False,
        ),
    ]
