# Generated by Django 4.2.1 on 2023-06-20 15:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_dateadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='dateupdate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date update'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.BigIntegerField(blank=True, verbose_name='Year book'),
        ),
    ]
