# Generated by Django 4.2.1 on 2023-06-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_dateupdate_alter_book_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.BigIntegerField(blank=True, default=100, verbose_name='Number of pages'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pereplet',
            field=models.CharField(blank=True, max_length=20, verbose_name='Pereplet book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='dateadd',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date add'),
        ),
        migrations.AlterField(
            model_name='book',
            name='dateupdate',
            field=models.DateTimeField(auto_now=True, verbose_name='Date update'),
        ),
    ]
