# Generated by Django 4.2.1 on 2023-06-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_pages_book_pereplet_alter_book_dateadd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='formatbook',
            field=models.CharField(blank=True, default='encyclopedia', max_length=30, verbose_name='format book'),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(default=987654321, verbose_name='ISBN book'),
            preserve_default=False,
        ),
    ]
