# Generated by Django 4.2.1 on 2023-06-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_book_agerestrict_book_ves_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='agerestrict',
            field=models.CharField(blank=True, default='6+', max_length=30, verbose_name='Age restrictions book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pereplet',
            field=models.CharField(blank=True, default='hardcover', max_length=20, verbose_name='Pereplet book'),
        ),
    ]
