# Generated by Django 4.2.1 on 2023-06-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0009_alter_series_name'),
        ('books', '0011_alter_book_agerestrict_alter_book_pereplet'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='books_publish', to='reference.publish', verbose_name='Publish'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='agerestrict',
            field=models.CharField(blank=True, default='6+', max_length=4, verbose_name='Age restrictions book'),
        ),
    ]
