# Generated by Django 4.2.1 on 2023-06-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_book_publish_alter_book_agerestrict'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.BigIntegerField(blank=True, default=1, verbose_name='Number of books'),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.BigIntegerField(blank=True, default=1, verbose_name='rating books'),
        ),
    ]
