# Generated by Django 4.2.1 on 2023-06-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_book_quantity_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='activ',
            field=models.BooleanField(default=False),
        ),
    ]
