# Generated by Django 4.2.1 on 2023-06-20 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_book_activ_alter_book_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='ISBN book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Number of pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ves',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='ves book'),
        ),
    ]
