# Generated by Django 4.2.1 on 2023-06-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_alter_book_isbn_alter_book_pages_alter_book_ves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ISBN book'),
        ),
    ]
