# Generated by Django 4.2.1 on 2023-06-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Number of pages'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ves',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ves book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Year book'),
        ),
    ]
