# Generated by Django 4.2.1 on 2023-07-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_alter_book_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='formatbook',
            field=models.CharField(blank=True, default='encyclopedi', max_length=30, verbose_name='format book'),
        ),
    ]
