# Generated by Django 4.2.1 on 2023-06-26 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0010_status'),
        ('orders', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='reference.status', verbose_name='Status'),
        ),
    ]
