# Generated by Django 4.2.1 on 2023-05-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Authors name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Genre description')),
            ],
        ),
    ]
