# Generated by Django 4.2.1 on 2023-05-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0002_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Author name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Author description')),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Publishing office')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Publishing office description')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.BigIntegerField(max_length=20, verbose_name='Series book')),
            ],
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
