# Generated by Django 4.2.1 on 2023-05-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_authors_publish_series_delete_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.BigIntegerField(verbose_name='Series book'),
        ),
    ]
