# Generated by Django 4.2.1 on 2023-05-24 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0004_alter_series_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
