# Generated by Django 4.2.1 on 2023-05-24 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0005_rename_genres_genre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Authors',
            new_name='Author',
        ),
    ]
