# Generated by Django 4.2.1 on 2023-06-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0006_rename_authors_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='picture',
            field=models.ImageField(default='-', upload_to='uploads/genre/', verbose_name='picture name'),
            preserve_default=False,
        ),
    ]
