# Generated by Django 4.2.1 on 2023-06-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0008_alter_genre_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Series book'),
        ),
    ]
