# Generated by Django 4.2.1 on 2023-07-11 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0010_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='picture',
        ),
    ]
